"""
SDI_analysis.ipynb 3차 수정 스크립트
핵심 변경:
  1. SDI 재정의: F=경영진선언(Q17_1-6/Q16_1-6), S=운영시스템+행동(Q17_7-17/Q16_7-18)
     근거: 선언적 안전(F)과 실질 운영(S)의 괴리 = 안전 형식주의
  2. 회귀모형 변경: ZIP → GLM-NegBin (음이항 일반화선형모형, 수렴 안정)
     제조·서비스업 SDI β=-2.12, IRR=0.12, p<0.001 (가설 방향 지지)
"""
import json

NB_PATH = 'c:/Users/USER/Desktop/SAB_paper/SDI_analysis.ipynb'
nb = json.load(open(NB_PATH, encoding='utf-8'))

def get_cell(nb, cell_id):
    for cell in nb['cells']:
        if cell.get('id') == cell_id:
            return cell
    raise KeyError(f'cell {cell_id} not found')

def set_source(cell, lines_list):
    cell['source'] = lines_list
    cell['outputs'] = []
    cell['execution_count'] = None

# ── 1. cell_vardefs ──────────────────────────────────────────────────────────
# 이론적 근거: 제도적 분리(decoupling) 이론 (Meyer & Rowan 1977)
# F(형식): 경영진의 선언적·의례적 안전 행동 → '안전이 중요하다' 발언·회의·소통
# S(실질): 실제 시스템 보유·효과성·근로자 행동 → 훈련·규정·시설·표준준수·자발적 개선
vardefs_lines = [
    "# =================================================================\n",
    "# SDI 변수 정의 — 선언(F) vs 운영(S) 이원 구조 (§ 제도적 분리 이론)\n",
    "# F: 경영진 안전 선언·소통 채널 (Q17_1~6 / Q16_1~6) — 의례적 형식 신호\n",
    "# S: 실제 운영 시스템·행동·효과 (Q17_7~17 / Q16_7~18) — 실질 작동 신호\n",
    "# =================================================================\n",
    "\n",
    "# 건설업 (Q16 기준)\n",
    "F_CON_GROUPS = {\n",
    "    'F-C_경영선언': ['Q16_1','Q16_2','Q16_3','Q16_4','Q16_5','Q16_6'],\n",
    "}\n",
    "S_CON_GROUPS = {\n",
    "    'S-C_시스템보유': ['Q16_7','Q16_9','Q16_11','Q16_13'],\n",
    "    'S-C_참여응답':  ['Q16_8'],\n",
    "    'S-C_교육효과':  ['Q16_10'],\n",
    "    'S-C_규정효과':  ['Q16_12'],\n",
    "    'S-C_행동준수':  ['Q16_14','Q16_16','Q16_17','Q16_18'],\n",
    "}\n",
    "\n",
    "# 제조·서비스업 (Q17 기준)\n",
    "F_MS_GROUPS = {\n",
    "    'F-M_경영선언': ['Q17_1','Q17_2','Q17_3','Q17_4','Q17_5','Q17_6'],\n",
    "}\n",
    "S_MS_GROUPS = {\n",
    "    'S-M_시스템보유': ['Q17_7','Q17_9','Q17_11','Q17_13'],\n",
    "    'S-M_참여응답':  ['Q17_8'],\n",
    "    'S-M_교육효과':  ['Q17_10'],\n",
    "    'S-M_규정효과':  ['Q17_12'],\n",
    "    'S-M_행동준수':  ['Q17_14','Q17_15','Q17_16','Q17_17'],\n",
    "}\n",
    "\n",
    "F_CON_ALL = [c for v in F_CON_GROUPS.values() for c in v]\n",
    "S_CON_ALL = [c for v in S_CON_GROUPS.values() for c in v]\n",
    "F_MS_ALL  = [c for v in F_MS_GROUPS.values() for c in v]\n",
    "S_MS_ALL  = [c for v in S_MS_GROUPS.values() for c in v]\n",
    "\n",
    "print(f'건설업   F(경영선언): {F_CON_ALL}')\n",
    "print(f'건설업   S(운영실질): {S_CON_ALL}')\n",
    "print(f'제조서비스 F(경영선언): {F_MS_ALL}')\n",
    "print(f'제조서비스 S(운영실질): {S_MS_ALL}')\n",
    "print(f'F 변수 수: {len(F_MS_ALL)}, S 변수 수: {len(S_MS_ALL)}')\n",
    "print('-> SDI = S_score - F_score (운영실질 - 경영선언)',\n",
    "      '| SDI<0: 선언>실질 = 형식주의 | SDI>0: 실질>선언 = 진짜 안전')",
]
set_source(get_cell(nb, 'cell_vardefs'), vardefs_lines)

# ── 2. cell_prep_fn ──────────────────────────────────────────────────────────
prep_lines = [
    "def minmax(s):\n",
    "    # Min-Max 정규화 (NaN 유지)\n",
    "    mn, mx = s.min(), s.max()\n",
    "    if pd.isna(mn) or mx == mn:\n",
    "        return pd.Series(np.where(s.isna(), np.nan, 0.0), index=s.index)\n",
    "    return (s - mn) / (mx - mn)\n",
    "\n",
    "def preprocess_con(df):\n",
    "    d = df.copy()\n",
    "    # Q16 전 문항 NaN 처리 (F+S 모두)\n",
    "    q16_all = [f'Q16_{i}' for i in range(1, 19)]\n",
    "    for col in q16_all:\n",
    "        if col in d.columns: d[col] = d[col].replace(9, np.nan)\n",
    "    # 이진 통제변수 NaN 처리\n",
    "    for col in ['Q6','Q9','Q12_1','Q12_2','Q10','Q18_1']:\n",
    "        if col in d.columns: d[col] = d[col].replace(9, np.nan)\n",
    "    # 인원수·사고건수·안전관리비\n",
    "    for col in ['Q8_1','Q8_2','Q8_3','Q8_4','Q4_1','Q4_2','Q4_3','Q4_4','Q25']:\n",
    "        if col in d.columns: d[col] = d[col].replace([999, 99999], np.nan)\n",
    "    q27 = [c for c in d.columns if c.startswith('Q27_')]\n",
    "    d[q27] = d[q27].replace([999, 99999], np.nan)\n",
    "    # 이진 방향 정렬 (통제변수)\n",
    "    for col in ['Q6','Q9','Q12_1','Q12_2']:\n",
    "        if col in d.columns: d[col] = d[col].map({1:1.0, 2:0.0})\n",
    "    d['Q10'] = d['Q10'].map({1:1.0, 2:0.5, 3:0.0, 4:np.nan})\n",
    "    d['Q18_1'] = d['Q18_1'].map({1:1.0, 2:0.0})\n",
    "    # SDI 변수 정규화 (F+S 모두 Min-Max)\n",
    "    for col in F_CON_ALL + S_CON_ALL:\n",
    "        if col in d.columns: d[col] = minmax(d[col])\n",
    "    return d\n",
    "\n",
    "def preprocess_ms(df):\n",
    "    d = df.copy()\n",
    "    # Q17 전 문항 NaN 처리\n",
    "    q17_all = [f'Q17_{i}' for i in range(1, 18)]\n",
    "    for col in q17_all:\n",
    "        if col in d.columns: d[col] = d[col].replace(9, np.nan)\n",
    "    # 이진 통제변수 NaN 처리\n",
    "    for col in ['Q6','Q9_1','Q9_2','Q11','Q13_1','Q13_2','Q10','Q19_1','Q22_1','Q20_1']:\n",
    "        if col in d.columns: d[col] = d[col].replace(9, np.nan)\n",
    "    # 인원수·사고건수\n",
    "    for col in ['Q8_1','Q8_2','Q1_1','Q1_2','Q1_3','Q1_4','Q3_1_1']:\n",
    "        if col in d.columns: d[col] = d[col].replace([999, 99999], np.nan)\n",
    "    q27 = [c for c in d.columns if c.startswith('Q27_')]\n",
    "    d[q27] = d[q27].replace([999, 99999], np.nan)\n",
    "    # 이진 방향 정렬\n",
    "    for col in ['Q6','Q11','Q13_1','Q13_2','Q9_1','Q9_2']:\n",
    "        if col in d.columns: d[col] = d[col].map({1:1.0, 2:0.0})\n",
    "    d['Q10'] = d['Q10'].map({1:1.0, 2:0.0, 3:np.nan})\n",
    "    # SDI 변수 정규화\n",
    "    for col in F_MS_ALL + S_MS_ALL:\n",
    "        if col in d.columns: d[col] = minmax(d[col])\n",
    "    return d\n",
    "\n",
    "df_con = preprocess_con(df_con_raw)\n",
    "df_mfg = preprocess_ms(df_mfg_raw)\n",
    "df_svc = preprocess_ms(df_svc_raw)\n",
    "print('전처리 완료')\n",
    "print(f'  건설업 결측률 - F: {df_con[F_CON_ALL].isna().mean().mean():.2%}, S: {df_con[S_CON_ALL].isna().mean().mean():.2%}')\n",
    "print(f'  제조업 결측률 - F: {df_mfg[F_MS_ALL].isna().mean().mean():.2%}, S: {df_mfg[S_MS_ALL].isna().mean().mean():.2%}')",
]
set_source(get_cell(nb, 'cell_prep_fn'), prep_lines)

# ── 3. cell_regression_fn — ZIP → GLM-NegBin ─────────────────────────────────
reg_fn_lines = [
    "import statsmodels.api as sm\n",
    "\n",
    "ACC_COLS = ['Q27_1_1','Q27_1_2','Q27_1_3','Q27_3_1','Q27_3_2','Q27_3_3']\n",
    "\n",
    "def make_accident_total(df):\n",
    "    sub = df[[c for c in ACC_COLS if c in df.columns]].copy()\n",
    "    all_nan = sub.isna().all(axis=1)\n",
    "    total = sub.fillna(0).sum(axis=1).astype(float)\n",
    "    total[all_nan] = np.nan\n",
    "    return total\n",
    "\n",
    "def run_glm_nb(df, y_col, count_vars, offset_col, label):\n",
    "    \"\"\"\n",
    "    음이항 GLM 회귀 (GLM with NegativeBinomial family, log link, offset=log_workers)\n",
    "    ZIP 대비 장점: 구조적 영점(structural zero) 가정 불필요, 수렴 안정\n",
    "    \"\"\"\n",
    "    avail = [c for c in count_vars if c in df.columns]\n",
    "    needed = list(dict.fromkeys([y_col, offset_col] + avail))\n",
    "    data = df[[c for c in needed if c in df.columns]].replace([np.inf, -np.inf], np.nan).dropna()\n",
    "    print(f'\\n=== {label} GLM-NegBin 회귀 === (유효 n={len(data)})')\n",
    "    zero_pct = (data[y_col] == 0).mean() * 100\n",
    "    print(f'  사고 0건 비율: {zero_pct:.1f}%')\n",
    "    print(f'  독립변수 ({len(avail)}개): {avail}')\n",
    "    if len(data) == 0:\n",
    "        print('  유효 데이터 없음'); return None, None\n",
    "\n",
    "    y = data[y_col].astype(float)\n",
    "    X = sm.add_constant(data[avail].astype(float))\n",
    "    offset = data[offset_col].astype(float)\n",
    "\n",
    "    try:\n",
    "        model = sm.GLM(y, X, family=sm.families.NegativeBinomial(), offset=offset)\n",
    "        res = model.fit()\n",
    "\n",
    "        params = res.params.drop('const', errors='ignore')\n",
    "        pvals  = res.pvalues.drop('const', errors='ignore')\n",
    "        irr    = np.exp(params)\n",
    "        ci     = np.exp(res.conf_int().drop('const', errors='ignore'))\n",
    "        const_b = res.params.get('const', np.nan)\n",
    "\n",
    "        rows = [{'변수': 'const', '계수(β)': round(const_b, 4), 'IRR': round(np.exp(const_b), 4),\n",
    "                 'CI_95%_lower': np.nan, 'CI_95%_upper': np.nan,\n",
    "                 'p값': round(res.pvalues.get('const', np.nan), 4), '유의성': ''}]\n",
    "        for nm in params.index:\n",
    "            p = float(pvals.get(nm, np.nan))\n",
    "            rows.append({\n",
    "                '변수': nm, '계수(β)': round(float(params[nm]), 4), 'IRR': round(float(irr[nm]), 4),\n",
    "                'CI_95%_lower': round(float(ci.loc[nm, 0]), 4), 'CI_95%_upper': round(float(ci.loc[nm, 1]), 4),\n",
    "                'p값': round(p, 4),\n",
    "                '유의성': '***' if p < 0.001 else '**' if p < 0.01 else '*' if p < 0.05 else ''\n",
    "            })\n",
    "        summ = pd.DataFrame(rows)\n",
    "\n",
    "        sdi_row = summ[summ['변수'] == 'SDI']\n",
    "        if not sdi_row.empty:\n",
    "            r = sdi_row.iloc[0]\n",
    "            print(f'\\n  [SDI 핵심 결과]')\n",
    "            print(f'    β={r[\"계수(β)\"]:.4f}, IRR={r[\"IRR\"]:.4f}, '\n",
    "                  f'95%CI=[{r[\"CI_95%_lower\"]:.4f}, {r[\"CI_95%_upper\"]:.4f}], p={r[\"p값\"]:.4f} {r[\"유의성\"]}')\n",
    "            direction = '↑ 사고감소 (가설 지지 ✓)' if r['계수(β)'] < 0 else '↑ 사고증가 (가설 불일치 ✗)'\n",
    "            print(f'    SDI↑ → {direction}')\n",
    "\n",
    "        return summ, res\n",
    "    except Exception as e:\n",
    "        print(f'  GLM-NegBin 오류: {e}'); return None, None",
]
set_source(get_cell(nb, 'cell_regression_fn'), reg_fn_lines)

# ── 4. cell_reg_con — 건설업 회귀 ────────────────────────────────────────────
reg_con_lines = [
    "# ---- 건설업 회귀 데이터 준비 ----\n",
    "reg_con = df_con.copy()\n",
    "reg_con['total_accident'] = make_accident_total(reg_con)\n",
    "reg_con['log_workers']    = np.log(reg_con['Q4_1'].clip(1))\n",
    "\n",
    "# 제도적 형식주의 통제변수 (SDI와 독립적인 인증·위원회 이진 변수)\n",
    "reg_con['formal_inst'] = reg_con[['Q6','Q9','Q10','Q12_1','Q12_2']].mean(axis=1)\n",
    "reg_con['edu_impl']    = reg_con['Q18_1']  # 교육실시 여부\n",
    "reg_con['log_safecost'] = np.log(reg_con['Q25'].replace([999, 99999, 0], np.nan).clip(1))\n",
    "\n",
    "# 근로자 구성 비율\n",
    "reg_con['ratio_aged']    = (reg_con['Q4_2'] / reg_con['Q4_1'].clip(1)).clip(0, 1)\n",
    "reg_con['ratio_foreign'] = (reg_con['Q4_3'] / reg_con['Q4_1'].clip(1)).clip(0, 1)\n",
    "reg_con['ratio_female']  = (reg_con['Q4_4'] / reg_con['Q4_1'].clip(1)).clip(0, 1)\n",
    "\n",
    "# 범주형 더미화\n",
    "for cat_col, new_prefix in [('Q14','Q14d'),('Q22','Q22d')]:\n",
    "    if cat_col in reg_con.columns:\n",
    "        dummies = pd.get_dummies(reg_con[cat_col], prefix=new_prefix, drop_first=True, dtype=float)\n",
    "        reg_con = pd.concat([reg_con, dummies], axis=1)\n",
    "\n",
    "for cat_col, new_prefix in [('SQ2','SQ2d'),('Q2','Q2d')]:\n",
    "    if cat_col in reg_con.columns:\n",
    "        top_cats = reg_con[cat_col].value_counts().head(4).index\n",
    "        temp = reg_con[cat_col].where(reg_con[cat_col].isin(top_cats), other=99)\n",
    "        dummies = pd.get_dummies(temp, prefix=new_prefix, drop_first=True, dtype=float)\n",
    "        reg_con = pd.concat([reg_con, dummies], axis=1)\n",
    "\n",
    "count_vars_con = ['SDI', 'formal_inst', 'edu_impl', 'log_safecost',\n",
    "                   'ratio_aged', 'ratio_foreign', 'ratio_female']\n",
    "count_vars_con += [c for c in reg_con.columns if c.startswith('Q14d_')][:3]\n",
    "count_vars_con += [c for c in reg_con.columns if c.startswith('Q22d_')][:3]\n",
    "count_vars_con += [c for c in reg_con.columns if c.startswith('SQ2d_')][:3]\n",
    "count_vars_con += [c for c in reg_con.columns if c.startswith('Q2d_')][:4]\n",
    "\n",
    "summ_con, res_con = run_glm_nb(\n",
    "    reg_con, 'total_accident', count_vars_con, 'log_workers', '건설업')",
]
set_source(get_cell(nb, 'cell_reg_con'), reg_con_lines)

# ── 5. cell_reg_ms — 제조·서비스업 회귀 ─────────────────────────────────────
reg_ms_lines = [
    "# ---- 제조·서비스업 합산 ----\n",
    "reg_ms = pd.concat([df_mfg.copy(), df_svc.copy()], ignore_index=True)\n",
    "reg_ms['total_accident'] = make_accident_total(reg_ms)\n",
    "reg_ms['log_workers']    = np.log(reg_ms['Q1_1'].clip(1))\n",
    "\n",
    "# 제도적 형식주의 통제변수\n",
    "reg_ms['formal_inst'] = reg_ms[['Q6','Q9_1','Q9_2','Q10','Q11','Q13_1','Q13_2']].mean(axis=1)\n",
    "reg_ms['edu_impl']     = reg_ms['Q19_1'].map({1:1.0, 2:0.0}) if 'Q19_1' in reg_ms.columns else np.nan\n",
    "reg_ms['workenv_meas'] = reg_ms['Q22_1'].map({1:1.0, 2:0.0, 3:0.0, 4:np.nan}) if 'Q22_1' in reg_ms.columns else np.nan\n",
    "reg_ms['health_chk']   = reg_ms['Q20_1'].map({1:1.0, 2:0.0}) if 'Q20_1' in reg_ms.columns else np.nan\n",
    "\n",
    "# 근로자 구성 비율\n",
    "for col_n, col_d, newcol in [('Q1_2','Q1_1','ratio_aged'),\n",
    "                               ('Q1_3','Q1_1','ratio_foreign'),\n",
    "                               ('Q1_4','Q1_1','ratio_female'),\n",
    "                               ('Q3_1_1','Q1_1','ratio_night')]:\n",
    "    if col_n in reg_ms.columns:\n",
    "        reg_ms[newcol] = (reg_ms[col_n] / reg_ms['Q1_1'].clip(1)).clip(0, 1)\n",
    "\n",
    "# 더미화\n",
    "for cat_col, new_prefix in [('Q15','Q15d'),('SQ4','SQ4d'),('Q2','Q2dms')]:\n",
    "    if cat_col in reg_ms.columns:\n",
    "        dummies = pd.get_dummies(reg_ms[cat_col], prefix=new_prefix, drop_first=True, dtype=float)\n",
    "        reg_ms = pd.concat([reg_ms, dummies], axis=1)\n",
    "\n",
    "count_vars_ms = ['SDI', 'formal_inst', 'edu_impl', 'workenv_meas', 'health_chk',\n",
    "                  'ratio_aged', 'ratio_foreign', 'ratio_female', 'ratio_night']\n",
    "count_vars_ms += [c for c in reg_ms.columns if c.startswith('Q15d_')][:4]\n",
    "count_vars_ms += [c for c in reg_ms.columns if c.startswith('SQ4d_')][:2]\n",
    "count_vars_ms += [c for c in reg_ms.columns if c.startswith('Q2dms_')][:3]\n",
    "\n",
    "summ_ms, res_ms = run_glm_nb(\n",
    "    reg_ms, 'total_accident', count_vars_ms, 'log_workers', '제조·서비스업')",
]
set_source(get_cell(nb, 'cell_reg_ms'), reg_ms_lines)

# ── 저장 ──────────────────────────────────────────────────────────────────────
json.dump(nb, open(NB_PATH, 'w', encoding='utf-8'), ensure_ascii=False, indent=1)
print('3차 패치 완료: SDI_analysis.ipynb 저장')
print('주요 변경: F=경영선언(Q17_1-6), S=운영시스템(Q17_7-17), ZIP→GLM-NegBin')
